# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{  secrets.GCP_PROJECT_ID  }}/${{ secrets.GCP_APP_NAME }}
    steps:
    
    -name: Login
     uses: google-github-actions/setup-gcloud@v0
     with:
      project_id: ${{ secrets.GCP_PROJECT_ID }}
      service_account_email: ${{secrets.GCP_EMAIL }}
      service_account_key: ${{ secrets.GCP_CREDENTIALS }}
    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . -t $IMAGE_NAME
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

    # Runs a single command using the runners shell
      - name: Build Docker Image
        run: docker build -t eugeniubraga/api:latest .

      - name: Docker Login
        run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u eugeniubraga --password-stdin

      - name: Docker Push
        run: docker push eugeniubraga/api:latest

      - name: Deploy Docker Image
        uses: appleboy/ssh-action@master
      -name: Install kubectl
        run: apt-get install kubectl
